name: Purpose
favicon: null
layout_spectrum: 0.4244317056145519
typography_spectrum: 0.364877394400537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6897671557962894
  lightness: 0.44253959762863815
  saturation: 0.10303340503014624
  rhythmicContrast: 0.7047642064280808
purpose: []
